site_name: zkEVM Documentation
site_url: https://iden3.github.io/zkEVM
theme:
  name: material
  palette:
    primary: blue
  # logo: assets/logo.png
  # favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
repo_url: https://github.com/iden3/zkevm
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/iden3io
    - icon: fontawesome/brands/github
      link: https://github.com/iden3/zkevm
    - icon: octicons/browser-24
      link: https://iden3.io/zkevm

nav:
  - Architecture:
    - Introduction: "zkEVM/architecture/introduction.md"
    - Simple VM: "zkEVM/architecture/simple-vm.md"  
    - Prover architecture: "zkEVM/architecture/prover-architecture.md"  
  - PIL:
    - Tutorial: "zkEVM/PIL/tutorial.md"
    - State Machines: "zkEVM/PIL/state-machines.md"
  - Tools & Optimizations:
    - Merkle Tree: "zkEVM/tools-optimizations/merkle-tree.md"
  - References: "zkEVM/references.md"

